<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<RootNamespace>FarmaGest.UI</RootNamespace>
		<AssemblyName>FarmaGest.UI</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FarmaGest.Negocio\FarmaGest.Negocio.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
		<PackageReference Include="WPF-UI" Version="3.0.5" />
		<PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
	</ItemGroup>

</Project>